
services:
  postgres:
    image: postgres:16.11-alpine3.23
    container_name: payment-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      TZ: Asia/Ho_Chi_Minh

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  broker:
    image: apache/kafka:3.7.0
    container_name: broker
    hostname: broker
    restart: unless-stopped

    ports:
      # Client bên ngoài Docker (localhost)
      - "9092:9092"

    environment:
      # ===== KRaft basic =====
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # ===== Listener security =====
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      # ===== Kafka lắng nghe bên trong container =====
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:29092,
        PLAINTEXT_HOST://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:29093

      # ===== Kafka advertise cho client =====
      # Docker internal -> broker:29092
      # External (local dev / prod edge) -> localhost:9092
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://broker:29092,
        PLAINTEXT_HOST://localhost:9092

      # ===== Inter broker & controller =====
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093

      # ===== System topics (single broker) =====
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # ===== Storage =====
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # ===== Cluster ID =====
      # Chỉ giữ nếu volume là mới. Nếu lỗi -> docker compose down -v
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    volumes:
      - kafka_data:/var/lib/kafka/data

    healthcheck:
      # PHẢI dùng listener nội bộ
      test:
        [
          "CMD-SHELL",
          "opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:29092 --list || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  akhq:
    image: tchiotludo/akhq:0.25.0
    container_name: payment-akhq
    restart: unless-stopped

    depends_on:
      broker:
        condition: service_healthy

    ports:
      - "${AKHQ_PORT:-8080}:8080"

    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-docker:
              properties:
                bootstrap.servers: "broker:29092"

volumes:
  postgres_data:
  kafka_data:
