// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/lta2705/Go-Payment-Gateway/internal/functionality"
	"github.com/lta2705/Go-Payment-Gateway/internal/handler"
	"github.com/lta2705/Go-Payment-Gateway/internal/middleware"
	"github.com/lta2705/Go-Payment-Gateway/internal/repository"
	"github.com/lta2705/Go-Payment-Gateway/internal/routes"
	"github.com/lta2705/Go-Payment-Gateway/internal/service"
	"github.com/lta2705/Go-Payment-Gateway/internal/worker"
	"github.com/lta2705/Go-Payment-Gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	dbConfig := config.LoadDBConfig()
	db := middleware.SetupDatabase(dbConfig)
	transactionRepository := repository.NewTransactionRepository(db)
	pollingService := service.NewPollingService(transactionRepository)
	kafkaProducerConfig := config.LoadKafkaProducerConfig()
	writer := middleware.CreateKafkaProducer(kafkaProducerConfig)
	cardService := service.NewCardService(transactionRepository, pollingService, writer)
	qrService := service.NewQRService(transactionRepository, pollingService)
	voidService := service.NewVoidService(transactionRepository, pollingService)
	refundService := service.NewRefundService(transactionRepository, pollingService)
	checkStatusService := service.NewCheckStatusService(transactionRepository)
	merchantCredentialsRepository := repository.NewMerchantCredentialsRepository(db)
	merchantCredentialsService := service.NewMerchantCredentialsService(merchantCredentialsRepository)
	transactionHandler := handler.NewTransactionHandler(cardService, qrService, voidService, refundService, checkStatusService, merchantCredentialsService)
	engine := routes.NewRouter(transactionHandler)
	kafkaProducerWorker := worker.NewProducerWorker(writer)
	producerService := functionality.NewProduceService(kafkaProducerWorker)
	kafkaConsumerConfig := config.LoadKafkaConsumerConfig()
	reader := middleware.CreateKafkaConsumer(kafkaConsumerConfig)
	kafkaConsumerWorker := worker.NewConsumerWorker(reader)
	consumerService := functionality.NewConsumerService(kafkaConsumerWorker, transactionRepository)
	app := NewApp(engine, producerService, consumerService)
	return app, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewTransactionRepository, repository.NewMerchantCredentialsRepository)

var serviceSet = wire.NewSet(service.NewCardService, service.NewQRService, service.NewVoidService, service.NewRefundService, service.NewCheckStatusService, service.NewPollingService, service.NewMerchantCredentialsService)

var ProducerSet = wire.NewSet(config.LoadKafkaProducerConfig, middleware.CreateKafkaProducer, worker.NewProducerWorker, functionality.NewProduceService)

var ConsumerSet = wire.NewSet(config.LoadKafkaConsumerConfig, middleware.CreateKafkaConsumer, worker.NewConsumerWorker, functionality.NewConsumerService)

var handlerSet = wire.NewSet(handler.NewTransactionHandler)

var databaseSet = wire.NewSet(config.LoadDBConfig, middleware.SetupDatabase)
