// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/lta2705/Go-Payment-Gateway/internal/handler"
	"github.com/lta2705/Go-Payment-Gateway/internal/middleware"
	"github.com/lta2705/Go-Payment-Gateway/internal/repository"
	"github.com/lta2705/Go-Payment-Gateway/internal/routes"
	"github.com/lta2705/Go-Payment-Gateway/internal/service"
	"github.com/lta2705/Go-Payment-Gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, error) {
	dbConfig := config.LoadDBConfig()
	db := middleware.SetupDatabase(dbConfig)
	transactionRepository := repository.NewTransactionRepository(db)
	logger, err := middleware.NewLogger()
	if err != nil {
		return nil, err
	}
	transactionService := service.NewTransactionService(transactionRepository, logger)
	transactionHandlerImpl := handler.NewTransactionHandler(transactionService, logger)
	engine := routes.NewRouter(transactionHandlerImpl)
	return engine, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewTransactionRepository)

var serviceSet = wire.NewSet(service.NewTransactionService, service.NewPollingService)

var handlerSet = wire.NewSet(handler.NewTransactionHandler)

var loggerSet = wire.NewSet(middleware.NewLogger)
